import { Filme } from './types';

export const FILMES_MOCK: Filme[] = [
  {
    GUID: "c4d8f591-37bg-5dd3-c8g7-f75e9981g8c7",
    nomeOriginal: "The Gold Rush",
    nomePortugues: "Em Busca do Ouro",
    ano: "1925",
    categoria: ["Comédia", "Mudo", "Aventura"],
    duracao: "1h35",
    sinopse: "Charlie Chaplin protagoniza esta obra-prima do cinema mudo como um garimpeiro solitário no Klondike que enfrenta o frio, a fome e rivais em busca de ouro. Uma das comédias mais icônicas da era silenciosa.",
    embedLink: '<iframe src="https://iframe.mediadelivery.net/embed/256964/c4d8f591-37bg-5dd3-c8g7-f75e9981g8c7?autoplay=false&loop=false&muted=false&preload=true&responsive=true" allowfullscreen="true"></iframe>',
    imagemUrl: "https://images.pexels.com/photos/16870831/pexels-photo-16870831.jpeg",
    assistencias: 2100,
    avaliacoes: { gostei: 245, gosteiMuito: 312, naoGostei: 18 }
  },
  {
    GUID: "d5e9g602-48ch-6ee4-d9h8-g86f0092h9d8",
    nomeOriginal: "Casablanca",
    nomePortugues: "Casablanca",
    ano: "1942",
    categoria: ["Drama", "Romance", "Guerra"],
    duracao: "1h42",
    sinopse: "Durante a Segunda Guerra Mundial, o americano Rick Blaine administra um café em Casablanca e reencontra sua antiga paixão Ilsa, agora casada com um líder da resistência. Um clássico eterno sobre amor e sacrifício.",
    embedLink: '<iframe src="https://iframe.mediadelivery.net/embed/256964/d5e9g602-48ch-6ee4-d9h8-g86f0092h9d8?autoplay=false&loop=false&muted=false&preload=true&responsive=true" allowfullscreen="true"></iframe>',
    imagemUrl: "https://images.pexels.com/photos/14268971/pexels-photo-14268971.jpeg",
    assistencias: 3800,
    avaliacoes: { gostei: 567, gosteiMuito: 891, naoGostei: 34 }
  },
  {
    GUID: "e6f0h713-59di-7ff5-e0i9-h97g1103i0e9",
    nomeOriginal: "North by Northwest",
    nomePortugues: "Intriga Internacional",
    ano: "1959",
    categoria: ["Suspense", "Ação"],
    duracao: "2h16",
    sinopse: "Cary Grant interpreta um executivo publicitário que é confundido com um agente do governo e perseguido por espiões. Hitchcock em sua melhor forma, com uma das cenas mais icônicas do cinema no Monte Rushmore.",
    embedLink: '<iframe src="https://iframe.mediadelivery.net/embed/256964/e6f0h713-59di-7ff5-e0i9-h97g1103i0e9?autoplay=false&loop=false&muted=false&preload=true&responsive=true" allowfullscreen="true"></iframe>',
    imagemUrl: "https://images.pexels.com/photos/22483588/pexels-photo-22483588.jpeg",
    assistencias: 1950,
    avaliacoes: { gostei: 198, gosteiMuito: 287, naoGostei: 29 }
  },
  {
    GUID: "f7g1i824-60ej-8gg6-f1j0-i08h2214j1f0",
    nomeOriginal: "The Public Enemy",
    nomePortugues: "O Inimigo Público",
    ano: "1931",
    categoria: ["Crime", "Drama"],
    duracao: "1h23",
    sinopse: "James Cagney em sua performance mais icônica como Tom Powers, um gângster durante a Lei Seca. Um retrato brutal e realista do crime organizado que definiu o gênero de filmes de gângster.",
    embedLink: '<iframe src="https://iframe.mediadelivery.net/embed/256964/f7g1i824-60ej-8gg6-f1j0-i08h2214j1f0?autoplay=false&loop=false&muted=false&preload=true&responsive=true" allowfullscreen="true"></iframe>',
    imagemUrl: "https://images.pexels.com/photos/16870831/pexels-photo-16870831.jpeg",
    assistencias: 1650,
    avaliacoes: { gostei: 145, gosteiMuito: 203, naoGostei: 47 }
  },
  {
    GUID: "g8h2j935-71fk-9hh7-g2k1-j19i3325k2g1",
    nomeOriginal: "Sunset Boulevard",
    nomePortugues: "Crepúsculo dos Deuses",
    ano: "1950",
    categoria: ["Drama", "Mistério"],
    duracao: "1h50",
    sinopse: "Billy Wilder dirige este noir clássico sobre um roteirista falido que se envolve com uma estrela esquecida do cinema mudo. Uma crítica mordaz à indústria cinematográfica de Hollywood.",
    embedLink: '<iframe src="https://iframe.mediadelivery.net/embed/256964/g8h2j935-71fk-9hh7-g2k1-j19i3325k2g1?autoplay=false&loop=false&muted=false&preload=true&responsive=true" allowfullscreen="true"></iframe>',
    imagemUrl: "https://images.pexels.com/photos/14268971/pexels-photo-14268971.jpeg",
    assistencias: 2250,
    avaliacoes: { gostei: 234, gosteiMuito: 356, naoGostei: 41 }
  },
  {
    GUID: "h9i3k046-82gl-0ii8-h3l2-k20j4436l3h2",
    nomeOriginal: "The Maltese Falcon",
    nomePortugues: "O Falcão Maltês",
    ano: "1941",
    categoria: ["Crime", "Mistério", "Suspense"],
    duracao: "1h40",
    sinopse: "Humphrey Bogart como o detetive Sam Spade em busca de uma estatueta valiosa. John Huston dirige este filme noir definitivo baseado no romance de Dashiell Hammett.",
    embedLink: '<iframe src="https://iframe.mediadelivery.net/embed/256964/h9i3k046-82gl-0ii8-h3l2-k20j4436l3h2?autoplay=false&loop=false&muted=false&preload=true&responsive=true" allowfullscreen="true"></iframe>',
    imagemUrl: "https://images.pexels.com/photos/22483588/pexels-photo-22483588.jpeg",
    assistencias: 1890,
    avaliacoes: { gostei: 167, gosteiMuito: 298, naoGostei: 35 }
  },
  {
    GUID: "i0j4l157-93hm-1jj9-i4m3-l31k5547m4i3",
    nomeOriginal: "Gone with the Wind",
    nomePortugues: "E o Vento Levou",
    ano: "1939",
    categoria: ["Drama", "Romance", "Guerra"],
    duracao: "3h58",
    sinopse: "Épico romântico ambientado durante a Guerra Civil Americana, seguindo Scarlett O'Hara e sua luta para salvar sua plantação. Vivien Leigh e Clark Gable em performances inesquecíveis.",
    embedLink: '<iframe src="https://iframe.mediadelivery.net/embed/256964/i0j4l157-93hm-1jj9-i4m3-l31k5547m4i3?autoplay=false&loop=false&muted=false&preload=true&responsive=true" allowfullscreen="true"></iframe>',
    imagemUrl: "https://images.pexels.com/photos/16870831/pexels-photo-16870831.jpeg",
    assistencias: 4200,
    avaliacoes: { gostei: 456, gosteiMuito: 678, naoGostei: 89 }
  },
  {
    GUID: "j1k5m268-04in-2kk0-j5n4-m42l6658n5j4",
    nomeOriginal: "Citizen Kane",
    nomePortugues: "Cidadão Kane",
    ano: "1941",
    categoria: ["Drama", "Mistério"],
    duracao: "1h59",
    sinopse: "Orson Welles dirige e protagoniza esta obra-prima sobre Charles Foster Kane, um magnata da mídia cuja vida é contada através de flashbacks após sua morte. Considerado por muitos o melhor filme de todos os tempos.",
    embedLink: '<iframe src="https://iframe.mediadelivery.net/embed/256964/j1k5m268-04in-2kk0-j5n4-m42l6658n5j4?autoplay=false&loop=false&muted=false&preload=true&responsive=true" allowfullscreen="true"></iframe>',
    imagemUrl: "https://images.pexels.com/photos/14268971/pexels-photo-14268971.jpeg",
    assistencias: 3900,
    avaliacoes: { gostei: 512, gosteiMuito: 823, naoGostei: 45 }
  },
  {
    GUID: "k2l6n379-15jo-3ll1-k6o5-n53m7769o6k5",
    nomeOriginal: "Some Like It Hot",
    nomePortugues: "Quanto Mais Quente Melhor",
    ano: "1959",
    categoria: ["Comédia", "Romance"],
    duracao: "2h01",
    sinopse: "Billy Wilder dirige esta comédia clássica com Tony Curtis e Jack Lemmon como músicos que se disfarçam de mulheres para escapar da máfia. Marilyn Monroe brilha como a doce Sugar Kane.",
    embedLink: '<iframe src="https://iframe.mediadelivery.net/embed/256964/k2l6n379-15jo-3ll1-k6o5-n53m7769o6k5?autoplay=false&loop=false&muted=false&preload=true&responsive=true" allowfullscreen="true"></iframe>',
    imagemUrl: "https://images.pexels.com/photos/22483588/pexels-photo-22483588.jpeg",
    assistencias: 2850,
    avaliacoes: { gostei: 456, gosteiMuito: 623, naoGostei: 67 }
  },
  {
    GUID: "l3m7o480-26kp-4mm2-l7p6-o64n8870p7l6",
    nomeOriginal: "The Wizard of Oz",
    nomePortugues: "O Mágico de Oz",
    ano: "1939",
    categoria: ["Fantasia", "Musical", "Aventura"],
    duracao: "1h42",
    sinopse: "Dorothy e seu cão Totó são transportados para a terra mágica de Oz, onde encontram personagens inesquecíveis em sua jornada pela Estrada de Tijolos Amarelos. Um clássico da era dourada de Hollywood.",
    embedLink: '<iframe src="https://iframe.mediadelivery.net/embed/256964/l3m7o480-26kp-4mm2-l7p6-o64n8870p7l6?autoplay=false&loop=false&muted=false&preload=true&responsive=true" allowfullscreen="true"></iframe>',
    imagemUrl: "https://images.pexels.com/photos/16870831/pexels-photo-16870831.jpeg",
    assistencias: 5100,
    avaliacoes: { gostei: 678, gosteiMuito: 1123, naoGostei: 89 }
  },
  {
    GUID: "m4n8p591-37lq-5nn3-m8q7-p75o9981q8m7",
    nomeOriginal: "Vertigo",
    nomePortugues: "Um Corpo Que Cai",
    ano: "1958",
    categoria: ["Suspense", "Romance", "Mistério"],
    duracao: "2h08",
    sinopse: "Alfred Hitchcock dirige James Stewart como um ex-policial que sofre de vertigem e se torna obcecado por uma mulher misteriosa interpretada por Kim Novak. Uma obra-prima do suspense psicológico.",
    embedLink: '<iframe src="https://iframe.mediadelivery.net/embed/256964/m4n8p591-37lq-5nn3-m8q7-p75o9981q8m7?autoplay=false&loop=false&muted=false&preload=true&responsive=true" allowfullscreen="true"></iframe>',
    imagemUrl: "https://images.pexels.com/photos/14268971/pexels-photo-14268971.jpeg",
    assistencias: 2670,
    avaliacoes: { gostei: 389, gosteiMuito: 567, naoGostei: 78 }
  },
  {
    GUID: "n5o9q602-48mr-6oo4-n9r8-q86p0092r9n8",
    nomeOriginal: "Singin' in the Rain",
    nomePortugues: "Cantando na Chuva",
    ano: "1952",
    categoria: ["Musical", "Comédia", "Romance"],
    duracao: "1h43",
    sinopse: "Gene Kelly, Donald O'Connor e Debbie Reynolds protagonizam este musical alegre sobre a transição do cinema mudo para o falado. Coreografias espetaculares e números musicais inesquecíveis.",
    embedLink: '<iframe src="https://iframe.mediadelivery.net/embed/256964/n5o9q602-48mr-6oo4-n9r8-q86p0092r9n8?autoplay=false&loop=false&muted=false&preload=true&responsive=true" allowfullscreen="true"></iframe>',
    imagemUrl: "https://images.pexels.com/photos/22483588/pexels-photo-22483588.jpeg",
    assistencias: 3420,
    avaliacoes: { gostei: 567, gosteiMuito: 789, naoGostei: 34 }
  },
  {
    GUID: "o6p0r713-59ns-7pp5-o0s9-r97q1103s0o9",
    nomeOriginal: "The Apartment",
    nomePortugues: "Se Meu Apartamento Falasse",
    ano: "1960",
    categoria: ["Comédia", "Drama", "Romance"],
    duracao: "2h05",
    sinopse: "Billy Wilder dirige Jack Lemmon como um funcionário que empresta seu apartamento para os casos extraconjugais de seus chefes, até se apaixonar por uma das mulheres envolvidas, interpretada por Shirley MacLaine.",
    embedLink: '<iframe src="https://iframe.mediadelivery.net/embed/256964/o6p0r713-59ns-7pp5-o0s9-r97q1103s0o9?autoplay=false&loop=false&muted=false&preload=true&responsive=true" allowfullscreen="true"></iframe>',
    imagemUrl: "https://images.pexels.com/photos/16870831/pexels-photo-16870831.jpeg",
    assistencias: 1890,
    avaliacoes: { gostei: 278, gosteiMuito: 456, naoGostei: 67 }
  },
  {
    GUID: "p7q1s824-60ot-8qq6-p1t0-s08r2214t1p0",
    nomeOriginal: "Psycho",
    nomePortugues: "Psicose",
    ano: "1960",
    categoria: ["Terror", "Suspense", "Mistério"],
    duracao: "1h49",
    sinopse: "Alfred Hitchcock revoluciona o cinema de terror com esta obra-prima sobre Marion Crane e sua fatídica parada no Motel Bates. Anthony Perkins é inesquecível como Norman Bates.",
    embedLink: '<iframe src="https://iframe.mediadelivery.net/embed/256964/p7q1s824-60ot-8qq6-p1t0-s08r2214t1p0?autoplay=false&loop=false&muted=false&preload=true&responsive=true" allowfullscreen="true"></iframe>',
    imagemUrl: "https://images.pexels.com/photos/14268971/pexels-photo-14268971.jpeg",
    assistencias: 3100,
    avaliacoes: { gostei: 445, gosteiMuito: 678, naoGostei: 123 }
  },
  {
    GUID: "q8r2t935-71pu-9rr7-q2u1-t19s3325u2q1",
    nomeOriginal: "Roman Holiday",
    nomePortugues: "A Princesa e o Plebeu",
    ano: "1953",
    categoria: ["Romance", "Comédia"],
    duracao: "1h58",
    sinopse: "Audrey Hepburn estrela ao lado de Gregory Peck nesta comédia romântica sobre uma princesa que escapa de suas obrigações reais por um dia em Roma. Performance que rendeu a Hepburn seu primeiro Oscar.",
    embedLink: '<iframe src="https://iframe.mediadelivery.net/embed/256964/q8r2t935-71pu-9rr7-q2u1-t19s3325u2q1?autoplay=false&loop=false&muted=false&preload=true&responsive=true" allowfullscreen="true"></iframe>',
    imagemUrl: "https://images.pexels.com/photos/22483588/pexels-photo-22483588.jpeg",
    assistencias: 2340,
    avaliacoes: { gostei: 389, gosteiMuito: 567, naoGostei: 45 }
  },
  {
    GUID: "r9s3u046-82qv-0ss8-r3v2-u20t4436v3r2",
    nomeOriginal: "The Third Man",
    nomePortugues: "O Terceiro Homem",
    ano: "1949",
    categoria: ["Suspense", "Drama", "Mistério"],
    duracao: "1h44",
    sinopse: "Carol Reed dirige este thriller noir ambientado na Viena pós-guerra. Joseph Cotten investiga o misterioso desaparecimento de seu amigo Harry Lime, interpretado brilhantemente por Orson Welles.",
    embedLink: '<iframe src="https://iframe.mediadelivery.net/embed/256964/r9s3u046-82qv-0ss8-r3v2-u20t4436v3r2?autoplay=false&loop=false&muted=false&preload=true&responsive=true" allowfullscreen="true"></iframe>',
    imagemUrl: "https://images.pexels.com/photos/16870831/pexels-photo-16870831.jpeg",
    assistencias: 1750,
    avaliacoes: { gostei: 234, gosteiMuito: 345, naoGostei: 56 }
  },
  {
    GUID: "s0t4v157-93rw-1tt9-s4w3-v31u5547w4s3",
    nomeOriginal: "Double Indemnity",
    nomePortugues: "Pacto de Sangue",
    ano: "1944",
    categoria: ["Crime", "Drama", "Suspense"],
    duracao: "1h47",
    sinopse: "Billy Wilder dirige este clássico film noir com Fred MacMurray como um vendedor de seguros que se envolve com Barbara Stanwyck em um esquema de assassinato e fraude. Roteiro baseado em James M. Cain.",
    embedLink: '<iframe src="https://iframe.mediadelivery.net/embed/256964/s0t4v157-93rw-1tt9-s4w3-v31u5547w4s3?autoplay=false&loop=false&muted=false&preload=true&responsive=true" allowfullscreen="true"></iframe>',
    imagemUrl: "https://images.pexels.com/photos/14268971/pexels-photo-14268971.jpeg",
    assistencias: 1950,
    avaliacoes: { gostei: 267, gosteiMuito: 398, naoGostei: 89 }
  },
  {
    GUID: "t1u5w268-04sx-2uu0-t5x4-w42v6658x5t4",
    nomeOriginal: "City Lights",
    nomePortugues: "Luzes da Cidade",
    ano: "1931",
    categoria: ["Comédia", "Romance", "Mudo"],
    duracao: "1h27",
    sinopse: "Charlie Chaplin dirige e protagoniza esta obra-prima do cinema mudo sobre um vagabundo que se apaixona por uma florista cega. Uma das comédias mais tocantes e poéticas já feitas.",
    embedLink: '<iframe src="https://iframe.mediadelivery.net/embed/256964/t1u5w268-04sx-2uu0-t5x4-w42v6658x5t4?autoplay=false&loop=false&muted=false&preload=true&responsive=true" allowfullscreen="true"></iframe>',
    imagemUrl: "https://images.pexels.com/photos/22483588/pexels-photo-22483588.jpeg",
    assistencias: 2780,
    avaliacoes: { gostei: 445, gosteiMuito: 656, naoGostei: 34 }
  },
  {
    GUID: "b3c9e480-26bf-4cc2-b7f6-e64d8870f7b6",
    nomeOriginal: "Noah's Ark",
    nomePortugues: "A Arca de Noé",
    ano: "1928",
    categoria: ["Drama", "Mudo"],
    duracao: "1h39",
    sinopse: "Noah's Ark, dirigido por Michael Curtiz em 1928, é uma epopeia cinematográfica do período silencioso que impressiona pela sua ambição e escopo. O filme intercala a narrativa bíblica da Arca de Noé com uma história contemporânea ambientada durante a Primeira Guerra Mundial, explorando temas de fé, sacrifício e redenção. Conhecido por suas impressionantes cenas de enchente, que usaram efeitos práticos grandiosos e até perigosos para os atores, Noah's Ark é uma combinação poderosa de espetáculo visual e narrativa emocional, refletindo o talento de Curtiz em criar obras impactantes. A produção é lembrada tanto por suas proezas técnicas quanto pelo impacto emocional, fazendo dela um marco importante no cinema mudo.",
    embedLink: '<iframe src="https://iframe.mediadelivery.net/embed/256964/b3c9e480-26bf-4cc2-b7f6-e64d8870f7b6?autoplay=false&loop=false&muted=false&preload=true&responsive=true" allowfullscreen="true"></iframe>',
    imagemUrl: "https://cdn.builder.io/api/v1/image/assets%2F4ef37becc21d46ae954f959bf9c6c3d4%2Ff5cc066748ac44e18ca386cb298e9135?format=webp&width=800",
    assistencias: 1850,
    avaliacoes: { gostei: 178, gosteiMuito: 289, naoGostei: 43 }
  },
  {
    GUID: "39ea0979-42fe-4d3c-b4b9-ba91370eac0f",
    nomeOriginal: "The Trap",
    nomePortugues: "A Armadilha",
    ano: "1922",
    categoria: ["Drama", "Suspense", "Western"],
    duracao: "53min",
    sinopse: "Dirigido por William Cameron Menzies, estrelado por Lon Chaney, Claire Adams e Ralph Lewis. Este thriller de 1922, baseado em uma história de Zane Grey, segue a história de um homem chamado Charley, que vive isolado em uma cabana nas montanhas, onde é surpreendido por uma série de eventos misteriosos que o envolvem em uma trama de traição e vingança. Quando ele salva uma jovem chamada Mary, que estava sendo perseguida, os dois se envolvem em um romance, mas logo Charley descobre que a jovem tem seus próprios segredos e que ele foi vítima de uma armadilha que pode comprometer sua liberdade e vida. A Armadilha é um exemplo do estilo de atuação intensa de Lon Chaney, que se tornou conhecido por sua habilidade de transformar suas expressões faciais e movimentos corporais para transmitir emoções complexas, sem necessidade de diálogos.",
    embedLink: '<iframe src="https://iframe.mediadelivery.net/embed/256964/39ea0979-42fe-4d3c-b4b9-ba91370eac0f?autoplay=false&loop=false&muted=false&preload=true&responsive=true" allowfullscreen="true"></iframe>',
    imagemUrl: "https://cdn.builder.io/api/v1/image/assets%2F4ef37becc21d46ae954f959bf9c6c3d4%2F07de9f98ceb9437da96f4a789dcb190f?format=webp&width=800",
    assistencias: 920,
    avaliacoes: { gostei: 145, gosteiMuito: 189, naoGostei: 67 }
  }
];

export const FILMES_DESTAQUE = FILMES_MOCK.slice(0, 3);

export const FILMES_POR_CATEGORIA = {
  'Ação': FILMES_MOCK.filter(f => f.categoria.includes('Ação')),
  'Romance': FILMES_MOCK.filter(f => f.categoria.includes('Romance')),
  'Drama': FILMES_MOCK.filter(f => f.categoria.includes('Drama')),
  'Crime': FILMES_MOCK.filter(f => f.categoria.includes('Crime')),
  'Suspense': FILMES_MOCK.filter(f => f.categoria.includes('Suspense')),
  'Comédia': FILMES_MOCK.filter(f => f.categoria.includes('Comédia')),
  'Musical': FILMES_MOCK.filter(f => f.categoria.includes('Musical')),
  'Terror': FILMES_MOCK.filter(f => f.categoria.includes('Terror')),
  'Mistério': FILMES_MOCK.filter(f => f.categoria.includes('Mistério')),
  'Fantasia': FILMES_MOCK.filter(f => f.categoria.includes('Fantasia')),
  'Guerra': FILMES_MOCK.filter(f => f.categoria.includes('Guerra')),
  'Mudo': FILMES_MOCK.filter(f => f.categoria.includes('Mudo')),
  'Western': FILMES_MOCK.filter(f => f.categoria.includes('Western')),
};

export const TOP_5_FILMES = FILMES_MOCK
  .sort((a, b) => (b.assistencias || 0) - (a.assistencias || 0))
  .slice(0, 5);
